### ISSUE TITLE
ansible: implement fork-based module execution

### ISSUE THREAD

**Issue by dw** [dw/mitogen#155]
Now we have received our first shared global state issue (#154), it's time to investigate forking to execute even standard modules. A quick chat with upstream suggests the intention is to *increase* rather than decrease the amount of global state in use, and that in the specific example of #154, a pull request to cure the issue would have been rejected.

There are a bunch of considerations involved here:

* Forking for every single module is provably wasteful, as the majority of modules are well written, and re-execute perfectly well.
* User modules almost certainly can never be trusted to reliably re-execute, so forking will always be applied to those.
* Consider a whitelist/blacklist approach, where forking is avoided where it's not necessary.
* All the forking work will be entirely reused to implement better asynchronous module execution support. (#105)
* Forking prior to importing the script's modules will result in repeat compilation cost being paid for every single iteration of e.g. a with_items loop. In the case of the built-in url helper library from module_utils, on my laptop this amounts to 250ms wasted per iteration.
* Execution must finally change to stop directly using Mitogen's import mechanism. Instead, the module script should be compiled once in the pre-fork process, and preserved for use with the ``exec`` statement in the child.

Ansible bits:

* [x] Mitogen must support forking a child, preserving any cached state from the parent.
* [x] run_module() uses router.fork() to trigger fork a child.
* [x] ~~Mitogen's ModuleFinder must differentiate between a list of directly related modules for a given module, and transitively imported modules. This information should be available in the target process so that imports can be executed prior to forking, but without triggering execution of the target module.~~ Moved to #187 
* [x] Replace module import mechanism abuse to load modules with the first cut of the generic module runner

Mitogen bits:

* [x] It must be possible to use the Router.fork() API from a child, necessitating moving those methods out of master.py into parent.py

* [x] It must be possible to gracefully shut down a single child context.

* [x] ~~Forking works differently depending on whether we're forking from the master process, or some child. For masters, retrieving the mitogen.core source code works differently to in children, where it is only available as a string retrieved from the existing Importer instance.~~ Moved to #188

* [x] We must eliminate the master roundtrip required to allocate an ID for the new child. Over a slow network, this could add a 200ms penalty to every single invocation. The simplest solution to that is to allocate blocks of IDs to children (e.g. 1000 at a time) during ALLOCATE_ID, allowing the roundtrip to be amortized over 1000 executions.

* [x] ~~Care must be taken to ensure the Importer works correctly in the child process. If we forked from the master, the child process must(?) actually grow or reuse the existing ModuleResponder from the master, or create an Importer that is preseeded with all the data that ModuleResponder contains.~~ Moved to #188

* [x] In children, the newly forked child process should probably reuse the existing Importer instance from the parent. Needs a lot of careful thought.

* [x] ADD_ROUTE must finally change so that it is child-generated rather than master generated. Again, this is to avoid paying another roundtrip penalty.

* [x] ADD_ROUTE will not wait for an upstream confirmation; instead upstreams will log a warning if they receive a conflicting route.

* [x] Consider introducing a new DEL_ROUTE operation that operates asynchronously just like ADD_ROUTE.
